### ISSUE TITLE
Create a pledge: send confirmation email

### ISSUE THREAD

**Issue by ryelle** [WordPress/five-for-the-future#10]
The pledge plugin already creates a draft page on submission, but it also needs to send a confirmation email to the pledge owner. This will contain some kind of one-time link to confirm that the pledge owner is a real person. Once the confirmation link is clicked, the pledge is published.

Optionally, this will alert somewhere for a moderator to review the pledge - this could block publish, or be done after the pledge is published.

**Comment by iandunn** [comment]
> Once the confirmation link is clicked, the pledge is published.

IIRC we need to wait until at least 1 linked contributor has verified the pledge before publishing it, so it seems like we'll need an additional piece of metadata to track whether or not the email address is verified, and then both conditions will need to be met in order to publish.

**Comment by coreymckrill** [comment]
🤔 
My understanding is that the pledge will be set to `publish` after it's confirmed, but it won't appear in the archive/list of pledges until there is at least one confirmed contributor.

**Comment by iandunn** [comment]
Ah, ok. That feels a bit more fragile, since we have to add that condition anywhere that pledges are displayed (now and in the future), REST API endpoints, etc, but in practice that probably won't be a big deal, so that WFM.

**Comment by coreymckrill** [comment]
Related: #13

**Comment by iandunn** [comment]
WIP - https://github.com/WordPress/five-for-the-future/issues/34#issuecomment-545758814

**Comment by iandunn** [comment]
🤔 , alternatively, I wonder if we should just ask contributors to use their w.org account for authentication & authorization here and everywhere else, rather than the tokens from #46. With contributors we don't have any of [the concerns  that led us to using auth tokens over accounts](https://github.com/WordPress/five-for-the-future/blob/147da5ae24352a03a3da9cbdaacf62ae77cc655b/plugins/wporg-5ftf/includes/email.php#L6-L10).

They'd still get a email asking them to confirm, but instead the link would just take them to their profile, or w.org/5, and they'd click a button there in order to confirm it. That may get tangled up in #29, though, so another way would be to use the email auth token, but additionally require that they be logged in, so contributor tokens would only be valid if the token is valid and they're logged in as the user the token was generated for. That might be a smoother UX as well?

@ryelle , @coreymckrill , what are your thoughts?

**Comment by coreymckrill** [comment]
If we had a front end page that was available on the 5ftF site when the viewer is logged into their wporg account, we could actually use it for both confirming a link to a pledge and for removing from a pledge. Here is my high-fidelity rendering:

![IMG_5976](https://user-images.githubusercontent.com/916023/67593655-83429c80-f717-11e9-8ff7-8b5b5ef2de0c.JPG)

Is this along the lines of what you're suggesting @iandunn ?

**Comment by iandunn** [comment]
I opened #51 to continue that discussion, so we can leave this closed after #46 was merged.
