### ISSUE TITLE
Prevent company pledges becoming a public without pledges

### ISSUE THREAD

**Issue by timiwahalahti** [WordPress/five-for-the-future#166]
Looks like company pledges receive some spam, and there is a number of company pages without any confirmed contributors.

Those pages should probably be not shown publicly, or at last have `no-index` to battle against using completely empty pages for blackhat SEO purposes.

**Comment by courtneyr-dev** [comment]
Is there a way to track if a company is pledging contribution via contributions to Meetups or WordCamps? It gets me thinking too about contributions via hosting an SLS (social learning space, the events on Learn).  Even speaking at those events.  

Are there means to contribute via 5FTF that aren't tied directly to a team?

**Comment by iandunn** [comment]
> Those pages should probably be not shown publicly, or at last have no-index

IIRC the reason pages are "published"  is so that the companies can edit their pledges. We don't require folks to login to w.org, and instead they use a company email address. So they have to be able to access a pledge directly via the URL.

It looks like pledges with `draft`, `pending`, and `deactivated` statuses already have `noindex, nofollow` meta tags. They're also excluded from the `/pledges` list.

For all companies, any links they put in their descriptions have `nofollow` added.

So, I think things are ok they way they are, unless I'm missing something.

**Comment by iandunn** [comment]
> track if a company is [contribution to] Meetups or WordCamps? 

WordCamp.org has a Meetup post type that the Community team uses to help organize things, and it lists all the organizers for a meetup. It only has their Meetup.com usernames though, so we'd need to build a way to map those to wordpress.org usernames. We already have something similar w/ GitHub, but it requires opt-in, so not everyone uses it.

I can't think of a good way to track other Meetup contributions, like speaking, but I'd like to start discussions with each team soon so they can pick out some things that they'd like to track.

For WordCamps, we do track usernames for lead organizers, various co-organizers ("wranglers"), and speakers. We could maybe also match up 5fTF companies with camp sponsors, which we track. 

> hosting an SLS. Even speaking at those events.

That's another thing that would benefit from mapping Meetup.com usernames to wordpress.org usernames.

> Are there means to contribute via 5FTF that aren't tied directly to a team?

I don't think so, since 5ftF is meant to give teams consistent "staff" to do the less glamorous, long-term work that is hard to maintain with volunteers.

There are lots of things that aren't done for teams that are definitely contributions to the WP _ecosystem_, and those are also critically important, but 5ftF has a specific purpose.

**Comment by timiwahalahti** [comment]
> WordCamp.org has a Meetup post type that the Community team uses to help organize things, and it lists all the organizers for a meetup. It only has their Meetup.com usernames though, so we'd need to build a way to map those to wordpress.org usernames. We already have something similar w/ GitHub, but it requires opt-in, so not everyone uses it.

Meetup post type also actually has fields for organiser wordpress.org usernames.

> I can't think of a good way to track other Meetup contributions, like speaking, but I'd like to start discussions with each team soon so they can pick out some things that they'd like to track.

Yeah, I think there's no feasible way to achieve this with Meetup.com. I'd suggest getting back to this after we've moved out from Meetup.com at some point... hopefully, someday.

**Comment by courtneyr-dev** [comment]
[Learn SLS](https://learn.wordpress.org/social-learning/) definitely are Meetup powered, and companies are contributing by facilitating staff to these. 

Whether tracking rolls into 5ftF or is somehow reflected through profile activity, it would be good to keep it visible.

**Comment by iandunn** [comment]
> Meetup post type also actually has fields for organiser wordpress.org usernames.

Doh, I forgot about that, thanks!

> [Learn SLS](https://learn.wordpress.org/social-learning/) definitely are Meetup powered, and companies are contributing by facilitating staff to these.
>
> Whether tracking rolls into 5ftF or is somehow reflected through profile activity, it would be good to keep it visible.

👍🏻  Contributions to Learn would be considered 5ftF contributions IMO, since Learn is an official project. 

I'm working on adding [`#props` to w.org profiles](https://make.wordpress.org/project/2022/03/16/proposal-to-remove-spam-dormant-five-for-the-future-pledges/), which is one way we can credit things like Meetup.com that are currently difficult to track. There may be some better ways too if we continue thinking about it.

**Comment by iandunn** [comment]
I opened #192 to discuss activity for meetup organizers. It doesn't seem like there's anything to do on the original topic, so I'm going to close this.

Feel free to reopen if I missed something though.
