### ISSUE TITLE
Update Usermeta with latest 5ftf contribution.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/five-for-the-future#189]
We want to query for inactive accounts in #27 and #210. In order to do so we should:

- [ ] Wait until #119 is decided, since that determines the criteria to use
- [ ]  Create safe list of activities that qualify as 5ftF contributions (activity in github.com/wordpress repos, posts/comments on Make blogs, WordCamp organizing, etc)
- [ ]  Add a "latest 5ftf contribution" meta field to usermeta. Update that with `time()` whenever a 5ftf contribution is added to their profile.
    - [ ] This should be centralized in wporg-profiles-activity-handler, rather than each individual notifier having to do it. 
    - [ ] Don't update it for non-contribution activity, like opening posts on support forums (and commenting on posts they opened), committing to personal plugins/themes, etc.
- [ ] Some things like GitHub activity wouldn't be covered by the Profiles handler, though, and would need do be updated separately.
    - [ ] document that in the centralized code, so future devs will know to update new sources that are added.

This would be more performant than having to query all their activity and filter it. It can also be used in https://github.com/WordPress/five-for-the-future/issues/129.

**Comment by StevenDufresne** [comment]
@iandunn Is there anything that is blocking this?

**Comment by iandunn** [comment]
I don't think so. It might be a good thing to do early on so that it has been populated for a lot of folks by the time we start sending out emails.

**Comment by iandunn** [comment]
For translate.w.org, I'd guess that these [projects](https://translate.wordpress.org/projects/) would count as 5ftF:

* Apps
* bbPress
* BuddyPress
* GlotPress
* Meta
* WordPress

And these would be considered ecosystem contributions:

* Patterns
* Plugins
* Themes

These would be ignored since they're not active
* Waiting
* Disabled Projects

It might be most simplest to setup a safelist for the 5ftf ones, and then have the rest be skipped by default.

**Comment by pkevan** [comment]
Mostly done in https://meta.trac.wordpress.org/changeset/13881 so closing.
