### ISSUE TITLE
Regularly email companies to prompt for updates

### ISSUE THREAD

**Issue by iandunn** [WordPress/five-for-the-future#211]
Similar to #27, it'd be good to email companies and ask them to keep their pledges up to date. That'd help team reps find active folks and keep stats accurate.

We could send an email to the company when we send an email to an inactive contributor that the company sponsors, or we could just send an email to everyone every ~6 months, regardless of activity their contributor activity.

**Comment by timiwahalahti** [comment]
I think approaching every company regularly would be a good idea. Maybe once a year would be enough tho?

The email could include a thank you for pledging their employee's time and subtle hint to pledge more :)

**Comment by angelasjin** [comment]
Yes! Instead of emailing a company every time we send an email to an inactive contributor, I think it would be preferable to send an email to the company thanking them for supporting employee contribution, and a gentle ask to review their pledged employees for accuracy, especially if they have had people leave or change roles. I think twice a year (so every six months) would be ideal. 

If we have a company with no pledges or where all pledges are inactive, are we able to separate that out for a different email? I think that email would be more along the lines of thanking them for the aspirational pledge, asking if they need support in getting involved, and then letting them know that if they don't respond within 60 days, that we'll deactivate their pledge (but that they can reactivate at any time!).

**Comment by iandunn** [comment]
> If we have a company with no pledges or where all pledges are inactive, are we able to separate that out for a different email?

Yeah, that's no problem 👍🏻

**Comment by iandunn** [comment]
Here are drafts for the emails, do y'all have any thoughts?

**Companies with active contributors:**

> Hi `{company name}`, this is a bi-annual reminder to please review your Five for the Future pledge if you haven't lately. Please make sure your list of contributors and their hours/teams are accurate. This is especially true if any folks at your company have left or changed roles recently.
>
> Having an accurate roster helps Make team representatives find contributors to work on projects.
>
> You can view your contributors by visiting `{url}`. To edit your pledge, click on the `Edit Pledge` link and enter `{email}`. 
>
> Thanks!

**Companies without any active contributors**

> Hi `{company name}`, we noticed that your Five for the Future pledge doesn't have any confirmed contributors right now. Would you like any help getting plugged into the WordPress project?
>
> If you're no longer able to sponsor a contributor, that's ok! We understand, and appreciate the effort you've made. You can deactivate your pledge by visiting `{url}`, clicking on the `Edit Pledge` link, and entering `{email}`. You can reactivate it at any time in the future by contacting us.
>
> If your pledge doesn't have any contributors in 2 months, then we'll automatically deactivate it.
>
> Thanks!

**Comment by iandunn** [comment]
>  if they don't respond within 60 days, [we'll] deactivate their pledge.

Is that going to be a manual or automated process? 

If automated, it'd probably be best to break that off into a separate issue, since it'll need additional work to make that happen.

**Comment by iandunn** [comment]
I opened #214 for deactivating them after 60 days.
