### ISSUE TITLE
Manage an existing pledge: Add way to deactivate the pledge

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/five-for-the-future#22]
Both the pledge creator and a 5ftF admin should have a way to deactivate a pledge, so that it won't appear in the pledge list anymore, and contributors linked to the pledge won't show as being associated with it anymore. This would essentially be deleting the pledge, but the details of the pledge would remain in the database for archival purposes.

* There should **not** be a way for the pledge creator to directly re-activate a pledge, since the pledge may have been deactivated due to inappropriate use.
* Keeping the pledges for archival purposes may introduce some GDPR considerations.

**Comment by ryelle** [comment]
#115 adds this functionality in wp-admin, but we still need a way for pledge owners to deactivate. Maybe something at the end of the Manage Pledge page, so they've already authenticated with the pledge token.

This also needs some copy, but this could work for now:

> **Remove Pledge**
>
> This will remove your pledge from the Five for the Future listing. You will not be able to reactivate it or submit a new pledge for this company. [some help text?]
>
> [Remove Pledge] button in danger-red, will do an Are you sure? message to confirm.

This should probably email the pledge owner confirming the removal, with a "contact [email] if this was a mistake"  message since they won't be able to reactivate on their own (but we can in wp-admin). This email should only go out on a self-service deactivation.

> … GDPR considerations

Do we need to create an issue for any GDPR concerns? If someone's wp.org account is deleted, the corresponding contrib post(s) still exist (and it causes some PHP notices).
