### ISSUE TITLE
Core Performance Team badge missing from org pages

### ISSUE THREAD

**Issue by jeffpaul** [WordPress/five-for-the-future#230]
Looking at https://wordpress.org/five-for-the-future/pledge/10up/ as an example, it includes https://profiles.wordpress.org/joemcgill/ and https://profiles.wordpress.org/jeffpaul/ and https://profiles.wordpress.org/peterwilsoncc/ all of whom have Core Performance badges but those don't flow up and have a Core Performance Team badge on the 10up org page.  I'm guessing this is because the Core Performance badges (Contributor, Team) have been newly added, but the handling probably does not exist on the 5ftF org pages?

**Comment by jeffpaul** [comment]
Looks like Core Performance needs to be added here: https://github.com/WordPress/five-for-the-future/blob/2880d80e12c7c4440ce06d41d7cd25e6388e9243/themes/wporg-5ftf/functions.php#L244

and here: https://github.com/WordPress/five-for-the-future/blob/2880d80e12c7c4440ce06d41d7cd25e6388e9243/themes/wporg-5ftf/css/components/_team-badges.scss#L2

**Comment by dd32** [comment]
>  I'm guessing this is because the Core Performance badges (Contributor, Team) have been newly added, but the handling probably does not exist on the 5ftF org pages?

That seems like a reasonable guess.

The performance team isn't included in the sponsored contributors team list either, ie. the sponsored contributors can't select it here:
https://profiles.wordpress.org/me/profile/edit/group/5/

That list is intentionally not the same as all teams, I don't recall the reason why that's the case. I think it might've been due to not all of the groups in the BP backend are actually contribution teams that a company can sponsor.

I believe these badges reflect the teams that members of the company have specified they contribute hours towards, not simply the badges that the members have received. ie. That's the teams listed in this highlighted section:

<img width="863" alt="Screenshot 2023-12-22 at 3 11 08 pm" src="https://github.com/WordPress/five-for-the-future/assets/767313/aa2f3ec6-4a64-4b71-b485-8079bcb8c274">

So this needs a two-part change:
 1. Contributors need to be able to specify they contribute hours to the team
 2. 5ftf needs the styles for the Core Perf badge

**Comment by iandunn** [comment]
> That list is intentionally not the same as all teams, I don't recall the reason why that's the case. I think it might've been due to not all of the groups in the BP backend are actually contribution teams that a company can sponsor.

IIRC, we left out some of the "closed" groups like Security and Plugin Review, since folks who don't contribute to those teams often mistakingly select them. In some cases that's because they _wrote_ a plugin, and didn't understand the distinction.

I created https://github.com/WordPress/five-for-the-future/issues/134 to address team members not having it chosen.
