### ISSUE TITLE
New Theme: Pledge your company button too big.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/five-for-the-future#278]
On the page https://wordpress.org/five-for-the-future-test/pledges/, the "Pledge your company" button is larger than the designs and distracting. Although we don't seem to have button styles that perfectly match the designs, we should probably use the `is-small` button variant.

| Test Site | Designs | `is-small` |
|--------|--------|-------|
| <img width="1162" alt="Screenshot 2024-09-03 at 9 12 20 AM" src="https://github.com/user-attachments/assets/3c1052b4-5b07-4a5b-9eb9-1af451e73ab8"> | <img width="686" alt="Screenshot 2024-09-03 at 9 12 38 AM" src="https://github.com/user-attachments/assets/76a875df-8196-4074-adf6-357c0b268dc7"> | <img width="1167" alt="Screenshot 2024-09-03 at 9 14 57 AM" src="https://github.com/user-attachments/assets/16eff182-42f9-4042-8484-9ee2b2e2beb0"> |

**Comment by ryelle** [comment]
@fcoveram Did the button styles change? I'm using the default filled button style but as Steve mentions, it's ~10px too tall.

**Comment by fcoveram** [comment]
I just checked, and I'm also using the [default style from the Design Library](https://www.figma.com/design/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?node-id=152-400&m=dev) in the mockups. Perhaps the default versions of the Figma library and code differ?

**Comment by ryelle** [comment]
> Perhaps the default versions of the Figma library and code differ?

That's my question— they must have matched at some point but something changed. Is it too big everywhere? for example, the buttons in content on https://wordpress.org/ & https://wordpress.org/download/.

**Comment by fcoveram** [comment]
I got the problem.

The buttons on wp.org and wp.org/download pages have the right padding (with just 2px of difference on the left and right sides). The difference between designs and production is the label's line-height. In the designs is `16px` whereas in front is `1.7`. That impacts the button's height.

I played with the value on the inspector, and a value of `1.3` looks good. But since this button is a site-wise component, I'm not fully aware of all the areas it will impact.

I'm drawn to apply the change suggested, but I'd like your thoughts first @ryelle?

**Comment by ryelle** [comment]
> I played with the value on the inspector, and a value of 1.3 looks good. But since this button is a site-wise component, I'm not fully aware of all the areas it will impact.

There shouldn't be anywhere where a button wraps to cause an issue, and even if so, 1.3 is still a readable height. I've opened [an issue in the parent theme to fix this](https://github.com/WordPress/wporg-parent-2021/issues/152), and it should cascade down to fix this issue, so I'll close this one.
