### ISSUE TITLE
New Theme: Homepage container spacing tight on mobile.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/five-for-the-future#280]
Can we add more spacing to the two containers?

- Join us in fueling WordPress
- Contributor experiences

## Screenshot
| Test Site | 
| ---- |
| <img width="522" alt="Screenshot 2024-09-03 at 9 33 40 AM" src="https://github.com/user-attachments/assets/497fa89f-0d57-48bb-bcda-e65c4952a4a9"> |  |

**Comment by ndiego** [comment]
The padding and margin is set to `--wp--preset--spacing--60`, which equates to `clamp(20px, calc(10vw - 40px), 80px)`. However the value `--wp--preset--spacing--60` for is `clamp(40px, calc(5vw + 10px), 60px)`. I wonder if the lower clamp value for `60` should be something like `50px` instead of `20`. 

Here's an example with this applied: 

| `clamp(50px, calc(10vw - 40px), 80px)` |
|-|
|<img width="435" alt="image" src="https://github.com/user-attachments/assets/1582aaff-38d5-4224-9833-e7b7b35b6053">|

**Comment by ryelle** [comment]
> The padding and margin is set to --wp--preset--spacing--60, which equates to clamp(20px, calc(10vw - 40px), 80px). However the value --wp--preset--spacing--50 for is clamp(40px, calc(5vw + 10px), 60px). I wonder if the lower clamp value for 60 should be something like 50px instead of 20.

Changing that will change it across the entire network, and IIRC that big jump was intentional to match mobile mockups early on in the process. I'm not opposed to changing that, but it would need to be a parent-theme issue with more testing.

For 5ftf, we could switch to "Medium (50)" which is `clamp(40px, calc(5vw + 10px), 60px)` — this matches the mobile mockup, though the desktop mockup uses 80px height, so it would be slightly shorter.

**Comment by ndiego** [comment]
> Changing that will change it across the entire network, and IIRC that big jump was intentional to match mobile mockups early on in the process. I'm not opposed to changing that, but it would need to be a parent-theme issue with more testing.

Ahh yeah, we probably should avoid that. I took a quick look at the WordPress.org homepage and it looks like `--wp--preset--spacing--60` is used for column gap. 

> For 5ftf, we could switch to "Medium (50)" which is clamp(40px, calc(5vw + 10px), 60px) — this matches the mobile mockup, though the desktop mockup uses 80px height, so it would be slightly shorter.

I used the inspector and set `--wp--preset--spacing--60` to `clamp(40px, calc(5vw + 10px), 60px)` to mock up this change. I think it looks pretty good.

**Comment by ndiego** [comment]
After a discussion with @fcoveram, I have gone ahead and updated the spacing on the homepage to use "Medium (50)"
