### ISSUE TITLE
Gap between profile image and org info is smaller

### ISSUE THREAD

**Issue by fcoveram** [WordPress/five-for-the-future#287]
URL where issue is: https://wordpress.org/five-for-the-future-test/my-pledges/

Browser you're using: Arc v1.57.2

## What do you see?

The gap between profile image and organization info is bigger than the design

![Screenshot of header in My pledges page with notes](https://github.com/user-attachments/assets/24bdcce0-8972-4435-8410-98413554ebc8)

## What should be changed?

The space should be `medium (40px)`

**Comment by ryelle** [comment]
We don't have a static 40px size, just the variables. Should this be a custom always-40px size? For reference, [these are our sizes](https://github.com/WordPress/wporg-parent-2021/?tab=readme-ov-file#spacing), relevant ones below (note that these scale, so at ~800px wide, the size is halfway between the two).

| Code name | mobile size | desktop size |
|---|---|---|
| Small (40)  | 30px |  50px |
| Medium (50) | 40px | 60px |
| Large (60)  | 20px | 80px |

(note: Large is used for spacing between columns, which is why it has such a large range)

I think you have a different mockup for the mobile layout, but I don't see an issue for it - so using a custom fixed space of 40px might be fine, since we'll drop to a single column (IIRC) on smaller screens.

**Comment by fcoveram** [comment]
I understand. Thanks for the documentation reminder.

Perhaps `small (40)` is even better given that the single column on mobile has a bigger space between this section and the following one where "Pending pledges" and the organization(s) info are.

**Comment by fcoveram** [comment]
Ticket created (#292) requesting the change on mobile.

**Comment by ryelle** [comment]
@fcoveram This is already using "Small (40)" for the gap (it's 50px at large on desktop size). Did you mean a different gap?

![Image](https://github.com/user-attachments/assets/2fd9c618-a554-4511-af92-4aebd5300d66)

**Comment by fcoveram** [comment]
If it's 50px on desktop then everything is fine 🙂
