### ISSUE TITLE
Manage contributors in wp-admin

### ISSUE THREAD

**Issue by ryelle** [WordPress/five-for-the-future#3]
This should be an editable form with all the Pledge meta. Site moderators will probably not need to change this, pledge owners will edit things from the front end.

Maybe we can reuse the front-end form?

**Comment by coreymckrill** [comment]
I'm thinking that the back end form will include include some slight differences from the front end, like a button to resend the email to confirm that the address associated with a pledge is legit.

**Comment by iandunn** [comment]
How often will we need to edit pledges for companies, and what kinds of edits will we need to make? Would it be worth getting a feel for those answers before investing any time here?

Resending the confirmation email could be a front-end feature, since that would allow pledge creators to do it without moderator intervention.

**Comment by coreymckrill** [comment]
If pledges start coming in before the [Manage milestone](https://github.com/WordPress/five-for-the-future/milestone/2) is complete, it will be helpful to have an admin UI where changes can be made.

I agree that resending the confirmation on the front-end would be a better workflow. It seemed more complicated to do it that way, but maybe that's not actually true. I didn't spend a lot of time thinking about it.

**Comment by coreymckrill** [comment]
Noting that this is already mostly done, except for the part for managing contributors connected to the pledge. So we can probably punt the remainder of this to a later milestone.
