### ISSUE TITLE
New Theme: Hide middot on pledge page when content is wrapped.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/five-for-the-future#313]
When viewing a pledge page on mobile, or tablet, there middot is visible but isn't separating content.

## Screenshots

URL: https://wordpress.org/five-for-the-future/pledge/whodunit/

<img width="399" alt="Screenshot 2024-09-13 at 9 46 04 AM" src="https://github.com/user-attachments/assets/6f39bd36-0e8d-4ecf-9173-59cd419b3bc1">

<img width="699" alt="Screenshot 2024-09-13 at 9 44 20 AM" src="https://github.com/user-attachments/assets/2b0a3a52-6b61-4810-ba6f-e202e5017b75">

**Comment by StevenDufresne** [comment]
Related, is "This organization contributes 5% of their resources to the WordPress project." really valuable if it shows up on every listing? 

It seems like that _byline_ should be specific to the company but that's a generic statement about all pledges.

**Comment by ryelle** [comment]
Since the URL is a dynamic length, we don't know when it wraps, so we can't hide this dynamically. Maybe a different content layout would be better?

> Related, is "This organization contributes 5% of their resources to the WordPress project." really valuable if it shows up on every listing?

+1 — I'm sure we want this on the page for content/SEO reasons, but maybe it could be in the main content section instead?

<img width="725" alt="Screenshot 2024-09-13 at 11 03 55 AM" src="https://github.com/user-attachments/assets/71617b1c-d8e5-4813-96d7-d81ea220216e">

**Comment by fcoveram** [comment]
I'm drawn to replacing the dot with a similar spacing gap to reinforce the content difference. The SEO reason sounds solid to keep the sentence.
