### ISSUE TITLE
Create "my pledges" page

### ISSUE THREAD

**Issue by iandunn** [WordPress/five-for-the-future#56]
This is where contributors will confirm pending pledges and remove themselves from pledges. For this milestone, all that's needed is the ability to confirm pending pledges.

See #29, #30, #51, #12

https://www.figma.com/file/OirvZ8jLK3CNzVHnmAYjbufc/Five-for-the-Future?node-id=664%3A24

**Comment by iandunn** [comment]
@ryelle , @coreymckrill , @melchoyce - does this line up w/ your understanding as well?

**Comment by iandunn** [comment]
Rough idea sketched out in https://github.com/WordPress/five-for-the-future/commit/029a6588c838c3596a4d5d24e419dd2d16d56768

**Comment by coreymckrill** [comment]
I wonder if pending pledges should have _both_ buttons. The confirm one and the one to remove, in case they don't want to confirm it.

**Comment by ryelle** [comment]
Gathering the discussions into one place, I want to confirm the flow here:

- A pledge is created + confirmed, and then contributors are emailed with their confirmation link.
- Rather than a special token for contributors as originally planned, they're given a link to a "My Pledges" page which uses the logged in user to find attached pledges.

So _this issue_ is to create that My Pledges page:

- A list of pledges for the logged in user
- A confirm button to publish the contribution (if not confirmed yet)
- A remove button to remove yourself from a pledge (this won't be built until later)

@melchoyce You've already designed the My Pledges page, the only "new" thing is that we might have two buttons instead of just the one "remove" button. I'm thinking we can use the default button style for Confirm? and circle back if we need to once the remove functionality is built.

**Comment by iandunn** [comment]
That's how I was picturing it, yeah.

**Comment by melchoyce** [comment]
Would "confirm" and "remove" ever exist together on the same pledge?

**Comment by iandunn** [comment]
Ah, yeah, that's a good point. When it's pending you should be able to either confirm or remove, and removing would be different than a confirmed pledge that was deactivated; it would be more like `rejected` or something. maybe we should have a distinct custom post status for that? we could also just trash those, but we might want that historical data.

**Comment by coreymckrill** [comment]
I think we should keep statuses simple for the contributor CPT. `pending`, `publish`, and `trash`.

**Comment by ryelle** [comment]
@melchoyce The answer is yes– if you have not confirmed your contribution yet, you would have both a "Confirm" and "Remove" button (or maybe "ignore", "reject" - something to get it out of your list without accepting it).

**Comment by melchoyce** [comment]
Maybe "Decline?" Seems more polite.

How's something like this?

![image](https://user-images.githubusercontent.com/2846578/67698457-c6ec0f00-f980-11e9-9152-2ab36fd7b1b4.png)

![image](https://user-images.githubusercontent.com/2846578/67698541-eaaf5500-f980-11e9-8cb0-6e923286c41d.png)

**Comment by ryelle** [comment]
@iandunn I've updated the styling, and I think everything is built out here, is that right? So I think we can close this issue.

**Comment by iandunn** [comment]
👍
