### ISSUE TITLE
Deactivated contributors/pledges should be visible in post list

### ISSUE THREAD

**Issue by iandunn** [WordPress/five-for-the-future#59]
Contributors and pledges have a custom `deactivated` post status,  but by default Core doesn't display that in the All Posts list, making it easy to mistake a deactivated contributor for an active one. We could add a ` - deactivated` string to the post name column, similar to what Core does with draft posts.

**Comment by coreymckrill** [comment]
One clarification: my intention was that only the plege CPT would have the custom `deactivated` post status. The thinking was that pledges could be deactivated/reactivated by the owner or by an admin without having to re-enter the pledge data or re-confirm contributors.

When contributors are removed from a pledge, however, there isn't really any data in the post type that needs to be retained, and the process of getting re-added would be identical to getting added the first time. So contributor posts can just be trashed instead of using a custom status.

**Comment by iandunn** [comment]
👍
