### ISSUE TITLE
Randomize order of pledges

### ISSUE THREAD

**Issue by iandunn** [WordPress/five-for-the-future#70]
That'd be more fair than alphabetical, etc. It might be complicated with pagination, though.

**Comment by coreymckrill** [comment]
I tested `order => rand` with pagination, and it doesn't work. Subsequent pages are completely random, rather than more posts from the original random set.

One way we could mitigate this might be to cache an array of post IDs that are in a random order, and then use `post__in => array()` and `order => post__in`. Then refresh the cache every 10 minutes or something.

**Comment by iandunn** [comment]
We won't need pagination for awhile, so I think we can go w/ `rand` and `numberposts => 30` for the launch, and then iterate on this shortly thereafter. I like the `post__in` idea.

**Comment by WPprodigy** [comment]
Quick note that the below is currently applying to all main queries on the site. Should probably be wrapped in that `$query->is_archive` conditional block?

https://github.com/WordPress/five-for-the-future/blob/1576a18d24cb9ace44b54808b2e896c3a26248d4/plugins/wporg-5ftf/includes/pledge.php#L275

And then once this is removed, the post_per_page is going to default to whatever is set at Settings > Readings. So that's something just to be aware of.

**Comment by WPprodigy** [comment]
And then here is the mysql seeded RAND() approach I was talking about: https://core.trac.wordpress.org/ticket/35692

Implementing it is as simple as `$query->set( 'orderby', 'RAND(123)' );`. But instead of `123`, we could have some cached `wp_rand()` value. The downside to this approach is that for the duration of the cached seed, the pledges will always show up in the same order. Perhaps there wouldn't be harm in setting just like a 5 minute cached seed value?

I found this to be an interesting approach: https://hugh.blog/2013/08/22/wordpress-random-post-order-with-correct-pagination/, but caching would get tricky so I'm not so sure this would work well at scale. Any similar ideas?

_________

Lastly, defaulting to random might Google not-so-happy. IANASEOE (I Am Not An SEO Export), but could perhaps need looking into to see if A: it is a problem, and B: if there is a way to default crawlers to have a different default sorting view.

**Comment by iandunn** [comment]
> But instead of 123, we could have some cached wp_rand() value

What about something like `wp_nonce_tick()`? That'd automatically stay consistent for 12 hours without needing to be stored in the db or anything.

> The downside to this approach is that for the duration of the cached seed, the pledges will always show up in the same order. Perhaps

🤔 Yeah, that's a good point. I definitely wouldn't want A8C to be stuck in the 1st position for 12 hours, since that'd lead to a lot of assumptions etc.

IMO pagination is a pretty awful UX anyway, so I'm tempted to just let it grow to a fairly long list 🤷‍♂

**Comment by dd32** [comment]
On the Themes Directory we use the date as the seed, ie. `RAND('2019-11-08')` changes once per day. Perhaps adding the hour would help, ie. `RAND('2019-11-08 13')` that way any one company is only there for an hour.

**Comment by dd32** [comment]
I should add though, that once you add randomness and pagination, it'll never be completely the same, and search engines will hate it because it's constantly different content :)

**Comment by ryelle** [comment]
> search engines will hate it because it's constantly different content

Do you know if they'll devalue the whole site for this, or just this one page?

I don't think it's a big deal if search engines don't see this page, since we don't want it to become an SEO target/keyword dump for the organizations on the page. So if it doesn't detract from the site as a whole, we can probably move forward with the hourly-seeded RAND function.
