### ISSUE TITLE
Cache direct database query: get_xprofile_contribution_data()

### ISSUE THREAD

**Issue by WPprodigy** [WordPress/five-for-the-future#88]
There's a direct database query done here: https://github.com/WordPress/five-for-the-future/blob/production/plugins/wporg-5ftf/includes/xprofile.php#L32-L43. This is run at least once on quite a few pages. I'm not sure what default caching logic exists on WPorg, but it's possible this wouldn't be going to object cache by default.

So I'm thinking this needs to be cached either in `get_xprofile_contribution_data()` itself, or in `get_aggregate_contributor_data_for_pledge` and `get_contributor_user_data()`.

I can submit an attempt, but I don't have access to very good sample data so I would be working kind of blind on this part.

**Comment by iandunn** [comment]
I don't think the 5ftF site will ever get a lot of traffic, but if we notice any performance issues then this could definitely be a good place to start.

w.org runs Memcached and hyperdb. I don't see any explicit caching of queries, but Memcached could be implicitly caching the function calls. TBH I've never needed to work with it much.

If we added explicit caching around the query, I think we'd want to use use transients, so that it works similarly in local environments that don't have object caching setup.

**Comment by pkevan** [comment]
Given the DB queries are relatively fast and infrequently called I think it's ok to close this, and revisit if necessary in the future.
