### ISSUE TITLE
Setup Slack ping groups for each team's contributors

### ISSUE THREAD

**Issue by iandunn** [WordPress/five-for-the-future#92]
Would it be useful for teams to have a Slack ping group for all of the contributors who have marked on their w.org profile that they contribute hours to that team every week?

This would serve a similar purpose to #69 , but could be helpful in meetings, or when trying to reach out to a large number of people to recruit them to work on a project. Just like #69, I'm thinking it'd include both sponsored folks and volunteers.

Props @coreymckrill for the idea.

cc @andreamiddleton, @ryelle

**Comment by ryelle** [comment]
Just to clarify because we've all talked through a few things, this would create "user groups" for each team that could be used like `@design-team Let's do a thing …` ?

Anyone can mention groups, there's no special restriction like with `@channel` or `@here`, so I think this would just become ripe for abuse. The folks who need to alert people are already able to use `/here` in the respective channels, so I don't know if this creates much benefit, considering the potential negative impact.

**Comment by iandunn** [comment]
I think it'd be more like `/committers`, which IIRC is restricted to the members of that group (or, if it's not, it can be, since it's controlled by a webhook callback on api.w.org).

**Comment by ryelle** [comment]
`@committers` appears to be a normal user group, not a slash-command. In any case, you're suggesting a slash-command that would be restricted to use by everyone in the group? That could still be a lot of potential people – maybe we should get some feedback from these teams before creating a way for everyone to mass-ping everyone else :)

**Comment by andreamiddleton** [comment]
I don't think we should retroactively sign up pledged contributors for any kind of automated attention-grabbing notification. I think we should test whether a passive, public report of what contributors have pledged time to what teams, would meet the needs of teams looking to recruit contributors to work on special projects.

**Comment by iandunn** [comment]
👍
